-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.InputObject exposing (..)

import Cambiatus.Enum.ContactType
import Cambiatus.Enum.Direction
import Cambiatus.Enum.OrderByFields
import Cambiatus.Enum.SearchByFields
import Cambiatus.Enum.TransferDirectionValue
import Cambiatus.Enum.VerificationType
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildActionsInput :
    (ActionsInputOptionalFields -> ActionsInputOptionalFields)
    -> ActionsInput
buildActionsInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { creator = Absent, isCompleted = Absent, validator = Absent, verificationType = Absent }
    in
    { creator = optionals____.creator, isCompleted = optionals____.isCompleted, validator = optionals____.validator, verificationType = optionals____.verificationType }


type alias ActionsInputOptionalFields =
    { creator : OptionalArgument String
    , isCompleted : OptionalArgument Bool
    , validator : OptionalArgument String
    , verificationType : OptionalArgument Cambiatus.Enum.VerificationType.VerificationType
    }


{-| Type for the ActionsInput input object.
-}
type alias ActionsInput =
    { creator : OptionalArgument String
    , isCompleted : OptionalArgument Bool
    , validator : OptionalArgument String
    , verificationType : OptionalArgument Cambiatus.Enum.VerificationType.VerificationType
    }


{-| Encode a ActionsInput into a value that can be used as an argument.
-}
encodeActionsInput : ActionsInput -> Value
encodeActionsInput input____ =
    Encode.maybeObject
        [ ( "creator", Encode.string |> Encode.optional input____.creator ), ( "isCompleted", Encode.bool |> Encode.optional input____.isCompleted ), ( "validator", Encode.string |> Encode.optional input____.validator ), ( "verificationType", Encode.enum Cambiatus.Enum.VerificationType.toString |> Encode.optional input____.verificationType ) ]


buildAddressUpdateInput :
    AddressUpdateInputRequiredFields
    -> (AddressUpdateInputOptionalFields -> AddressUpdateInputOptionalFields)
    -> AddressUpdateInput
buildAddressUpdateInput required____ fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { number = Absent }
    in
    { cityId = required____.cityId, countryId = required____.countryId, neighborhoodId = required____.neighborhoodId, number = optionals____.number, stateId = required____.stateId, street = required____.street, zip = required____.zip }


type alias AddressUpdateInputRequiredFields =
    { cityId : Cambiatus.ScalarCodecs.Id
    , countryId : Cambiatus.ScalarCodecs.Id
    , neighborhoodId : Cambiatus.ScalarCodecs.Id
    , stateId : Cambiatus.ScalarCodecs.Id
    , street : String
    , zip : String
    }


type alias AddressUpdateInputOptionalFields =
    { number : OptionalArgument String }


{-| Type for the AddressUpdateInput input object.
-}
type alias AddressUpdateInput =
    { cityId : Cambiatus.ScalarCodecs.Id
    , countryId : Cambiatus.ScalarCodecs.Id
    , neighborhoodId : Cambiatus.ScalarCodecs.Id
    , number : OptionalArgument String
    , stateId : Cambiatus.ScalarCodecs.Id
    , street : String
    , zip : String
    }


{-| Encode a AddressUpdateInput into a value that can be used as an argument.
-}
encodeAddressUpdateInput : AddressUpdateInput -> Value
encodeAddressUpdateInput input____ =
    Encode.maybeObject
        [ ( "cityId", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) input____.cityId |> Just ), ( "countryId", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) input____.countryId |> Just ), ( "neighborhoodId", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) input____.neighborhoodId |> Just ), ( "number", Encode.string |> Encode.optional input____.number ), ( "stateId", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) input____.stateId |> Just ), ( "street", Encode.string input____.street |> Just ), ( "zip", Encode.string input____.zip |> Just ) ]


buildChecksInput :
    (ChecksInputOptionalFields -> ChecksInputOptionalFields)
    -> ChecksInput
buildChecksInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { validator = Absent }
    in
    { validator = optionals____.validator }


type alias ChecksInputOptionalFields =
    { validator : OptionalArgument String }


{-| Type for the ChecksInput input object.
-}
type alias ChecksInput =
    { validator : OptionalArgument String }


{-| Encode a ChecksInput into a value that can be used as an argument.
-}
encodeChecksInput : ChecksInput -> Value
encodeChecksInput input____ =
    Encode.maybeObject
        [ ( "validator", Encode.string |> Encode.optional input____.validator ) ]


buildClaimsFilter :
    (ClaimsFilterOptionalFields -> ClaimsFilterOptionalFields)
    -> ClaimsFilter
buildClaimsFilter fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { claimer = Absent, direction = Absent, status = Absent }
    in
    { claimer = optionals____.claimer, direction = optionals____.direction, status = optionals____.status }


type alias ClaimsFilterOptionalFields =
    { claimer : OptionalArgument String
    , direction : OptionalArgument Cambiatus.Enum.Direction.Direction
    , status : OptionalArgument String
    }


{-| Type for the ClaimsFilter input object.
-}
type alias ClaimsFilter =
    { claimer : OptionalArgument String
    , direction : OptionalArgument Cambiatus.Enum.Direction.Direction
    , status : OptionalArgument String
    }


{-| Encode a ClaimsFilter into a value that can be used as an argument.
-}
encodeClaimsFilter : ClaimsFilter -> Value
encodeClaimsFilter input____ =
    Encode.maybeObject
        [ ( "claimer", Encode.string |> Encode.optional input____.claimer ), ( "direction", Encode.enum Cambiatus.Enum.Direction.toString |> Encode.optional input____.direction ), ( "status", Encode.string |> Encode.optional input____.status ) ]


buildCommunityUpdateInput :
    (CommunityUpdateInputOptionalFields -> CommunityUpdateInputOptionalFields)
    -> CommunityUpdateInput
buildCommunityUpdateInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { contacts = Absent, hasNews = Absent }
    in
    { contacts = optionals____.contacts, hasNews = optionals____.hasNews }


type alias CommunityUpdateInputOptionalFields =
    { contacts : OptionalArgument (List ContactInput)
    , hasNews : OptionalArgument Bool
    }


{-| Type for the CommunityUpdateInput input object.
-}
type alias CommunityUpdateInput =
    { contacts : OptionalArgument (List ContactInput)
    , hasNews : OptionalArgument Bool
    }


{-| Encode a CommunityUpdateInput into a value that can be used as an argument.
-}
encodeCommunityUpdateInput : CommunityUpdateInput -> Value
encodeCommunityUpdateInput input____ =
    Encode.maybeObject
        [ ( "contacts", (encodeContactInput |> Encode.list) |> Encode.optional input____.contacts ), ( "hasNews", Encode.bool |> Encode.optional input____.hasNews ) ]


buildContactInput :
    (ContactInputOptionalFields -> ContactInputOptionalFields)
    -> ContactInput
buildContactInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { externalId = Absent, label = Absent, type_ = Absent }
    in
    { externalId = optionals____.externalId, label = optionals____.label, type_ = optionals____.type_ }


type alias ContactInputOptionalFields =
    { externalId : OptionalArgument String
    , label : OptionalArgument String
    , type_ : OptionalArgument Cambiatus.Enum.ContactType.ContactType
    }


{-| Type for the ContactInput input object.
-}
type alias ContactInput =
    { externalId : OptionalArgument String
    , label : OptionalArgument String
    , type_ : OptionalArgument Cambiatus.Enum.ContactType.ContactType
    }


{-| Encode a ContactInput into a value that can be used as an argument.
-}
encodeContactInput : ContactInput -> Value
encodeContactInput input____ =
    Encode.maybeObject
        [ ( "externalId", Encode.string |> Encode.optional input____.externalId ), ( "label", Encode.string |> Encode.optional input____.label ), ( "type", Encode.enum Cambiatus.Enum.ContactType.toString |> Encode.optional input____.type_ ) ]


buildCountryInput :
    CountryInputRequiredFields
    -> CountryInput
buildCountryInput required____ =
    { name = required____.name }


type alias CountryInputRequiredFields =
    { name : String }


{-| Type for the CountryInput input object.
-}
type alias CountryInput =
    { name : String }


{-| Encode a CountryInput into a value that can be used as an argument.
-}
encodeCountryInput : CountryInput -> Value
encodeCountryInput input____ =
    Encode.maybeObject
        [ ( "name", Encode.string input____.name |> Just ) ]


buildKycDataUpdateInput :
    KycDataUpdateInputRequiredFields
    -> KycDataUpdateInput
buildKycDataUpdateInput required____ =
    { countryId = required____.countryId, document = required____.document, documentType = required____.documentType, phone = required____.phone, userType = required____.userType }


type alias KycDataUpdateInputRequiredFields =
    { countryId : Cambiatus.ScalarCodecs.Id
    , document : String
    , documentType : String
    , phone : String
    , userType : String
    }


{-| Type for the KycDataUpdateInput input object.
-}
type alias KycDataUpdateInput =
    { countryId : Cambiatus.ScalarCodecs.Id
    , document : String
    , documentType : String
    , phone : String
    , userType : String
    }


{-| Encode a KycDataUpdateInput into a value that can be used as an argument.
-}
encodeKycDataUpdateInput : KycDataUpdateInput -> Value
encodeKycDataUpdateInput input____ =
    Encode.maybeObject
        [ ( "countryId", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) input____.countryId |> Just ), ( "document", Encode.string input____.document |> Just ), ( "documentType", Encode.string input____.documentType |> Just ), ( "phone", Encode.string input____.phone |> Just ), ( "userType", Encode.string input____.userType |> Just ) ]


buildMembersFilterInput :
    (MembersFilterInputOptionalFields -> MembersFilterInputOptionalFields)
    -> MembersFilterInput
buildMembersFilterInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { orderDirection = Absent, orderMembersBy = Absent, searchMembersBy = Absent, searchString = Absent }
    in
    { orderDirection = optionals____.orderDirection, orderMembersBy = optionals____.orderMembersBy, searchMembersBy = optionals____.searchMembersBy, searchString = optionals____.searchString }


type alias MembersFilterInputOptionalFields =
    { orderDirection : OptionalArgument Cambiatus.Enum.Direction.Direction
    , orderMembersBy : OptionalArgument Cambiatus.Enum.OrderByFields.OrderByFields
    , searchMembersBy : OptionalArgument (List (Maybe Cambiatus.Enum.SearchByFields.SearchByFields))
    , searchString : OptionalArgument String
    }


{-| Type for the MembersFilterInput input object.
-}
type alias MembersFilterInput =
    { orderDirection : OptionalArgument Cambiatus.Enum.Direction.Direction
    , orderMembersBy : OptionalArgument Cambiatus.Enum.OrderByFields.OrderByFields
    , searchMembersBy : OptionalArgument (List (Maybe Cambiatus.Enum.SearchByFields.SearchByFields))
    , searchString : OptionalArgument String
    }


{-| Encode a MembersFilterInput into a value that can be used as an argument.
-}
encodeMembersFilterInput : MembersFilterInput -> Value
encodeMembersFilterInput input____ =
    Encode.maybeObject
        [ ( "orderDirection", Encode.enum Cambiatus.Enum.Direction.toString |> Encode.optional input____.orderDirection ), ( "orderMembersBy", Encode.enum Cambiatus.Enum.OrderByFields.toString |> Encode.optional input____.orderMembersBy ), ( "searchMembersBy", (Encode.enum Cambiatus.Enum.SearchByFields.toString |> Encode.maybe |> Encode.list) |> Encode.optional input____.searchMembersBy ), ( "searchString", Encode.string |> Encode.optional input____.searchString ) ]


buildNewCommunityInput :
    NewCommunityInputRequiredFields
    -> NewCommunityInput
buildNewCommunityInput required____ =
    { symbol = required____.symbol }


type alias NewCommunityInputRequiredFields =
    { symbol : String }


{-| Type for the NewCommunityInput input object.
-}
type alias NewCommunityInput =
    { symbol : String }


{-| Encode a NewCommunityInput into a value that can be used as an argument.
-}
encodeNewCommunityInput : NewCommunityInput -> Value
encodeNewCommunityInput input____ =
    Encode.maybeObject
        [ ( "symbol", Encode.string input____.symbol |> Just ) ]


buildProductsFilterInput :
    (ProductsFilterInputOptionalFields -> ProductsFilterInputOptionalFields)
    -> ProductsFilterInput
buildProductsFilterInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { account = Absent, categoriesIds = Absent, inStock = Absent }
    in
    { account = optionals____.account, categoriesIds = optionals____.categoriesIds, inStock = optionals____.inStock }


type alias ProductsFilterInputOptionalFields =
    { account : OptionalArgument String
    , categoriesIds : OptionalArgument (List (Maybe Int))
    , inStock : OptionalArgument Bool
    }


{-| Type for the ProductsFilterInput input object.
-}
type alias ProductsFilterInput =
    { account : OptionalArgument String
    , categoriesIds : OptionalArgument (List (Maybe Int))
    , inStock : OptionalArgument Bool
    }


{-| Encode a ProductsFilterInput into a value that can be used as an argument.
-}
encodeProductsFilterInput : ProductsFilterInput -> Value
encodeProductsFilterInput input____ =
    Encode.maybeObject
        [ ( "account", Encode.string |> Encode.optional input____.account ), ( "categoriesIds", (Encode.int |> Encode.maybe |> Encode.list) |> Encode.optional input____.categoriesIds ), ( "inStock", Encode.bool |> Encode.optional input____.inStock ) ]


buildPushSubscriptionInput :
    PushSubscriptionInputRequiredFields
    -> PushSubscriptionInput
buildPushSubscriptionInput required____ =
    { authKey = required____.authKey, endpoint = required____.endpoint, pKey = required____.pKey }


type alias PushSubscriptionInputRequiredFields =
    { authKey : String
    , endpoint : String
    , pKey : String
    }


{-| Type for the PushSubscriptionInput input object.
-}
type alias PushSubscriptionInput =
    { authKey : String
    , endpoint : String
    , pKey : String
    }


{-| Encode a PushSubscriptionInput into a value that can be used as an argument.
-}
encodePushSubscriptionInput : PushSubscriptionInput -> Value
encodePushSubscriptionInput input____ =
    Encode.maybeObject
        [ ( "authKey", Encode.string input____.authKey |> Just ), ( "endpoint", Encode.string input____.endpoint |> Just ), ( "pKey", Encode.string input____.pKey |> Just ) ]


buildReadNotificationInput :
    ReadNotificationInputRequiredFields
    -> ReadNotificationInput
buildReadNotificationInput required____ =
    { id = required____.id }


type alias ReadNotificationInputRequiredFields =
    { id : Int }


{-| Type for the ReadNotificationInput input object.
-}
type alias ReadNotificationInput =
    { id : Int }


{-| Encode a ReadNotificationInput into a value that can be used as an argument.
-}
encodeReadNotificationInput : ReadNotificationInput -> Value
encodeReadNotificationInput input____ =
    Encode.maybeObject
        [ ( "id", Encode.int input____.id |> Just ) ]


buildSubcategoryInput :
    SubcategoryInputRequiredFields
    -> SubcategoryInput
buildSubcategoryInput required____ =
    { id = required____.id, position = required____.position }


type alias SubcategoryInputRequiredFields =
    { id : Int
    , position : Int
    }


{-| Type for the SubcategoryInput input object.
-}
type alias SubcategoryInput =
    { id : Int
    , position : Int
    }


{-| Encode a SubcategoryInput into a value that can be used as an argument.
-}
encodeSubcategoryInput : SubcategoryInput -> Value
encodeSubcategoryInput input____ =
    Encode.maybeObject
        [ ( "id", Encode.int input____.id |> Just ), ( "position", Encode.int input____.position |> Just ) ]


buildTransferDirection :
    (TransferDirectionOptionalFields -> TransferDirectionOptionalFields)
    -> TransferDirection
buildTransferDirection fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { direction = Absent, otherAccount = Absent }
    in
    { direction = optionals____.direction, otherAccount = optionals____.otherAccount }


type alias TransferDirectionOptionalFields =
    { direction : OptionalArgument Cambiatus.Enum.TransferDirectionValue.TransferDirectionValue
    , otherAccount : OptionalArgument String
    }


{-| Type for the TransferDirection input object.
-}
type alias TransferDirection =
    { direction : OptionalArgument Cambiatus.Enum.TransferDirectionValue.TransferDirectionValue
    , otherAccount : OptionalArgument String
    }


{-| Encode a TransferDirection into a value that can be used as an argument.
-}
encodeTransferDirection : TransferDirection -> Value
encodeTransferDirection input____ =
    Encode.maybeObject
        [ ( "direction", Encode.enum Cambiatus.Enum.TransferDirectionValue.toString |> Encode.optional input____.direction ), ( "otherAccount", Encode.string |> Encode.optional input____.otherAccount ) ]


buildTransferFilter :
    (TransferFilterOptionalFields -> TransferFilterOptionalFields)
    -> TransferFilter
buildTransferFilter fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { communityId = Absent, date = Absent, direction = Absent }
    in
    { communityId = optionals____.communityId, date = optionals____.date, direction = optionals____.direction }


type alias TransferFilterOptionalFields =
    { communityId : OptionalArgument String
    , date : OptionalArgument Cambiatus.ScalarCodecs.Date
    , direction : OptionalArgument TransferDirection
    }


{-| Type for the TransferFilter input object.
-}
type alias TransferFilter =
    { communityId : OptionalArgument String
    , date : OptionalArgument Cambiatus.ScalarCodecs.Date
    , direction : OptionalArgument TransferDirection
    }


{-| Encode a TransferFilter into a value that can be used as an argument.
-}
encodeTransferFilter : TransferFilter -> Value
encodeTransferFilter input____ =
    Encode.maybeObject
        [ ( "communityId", Encode.string |> Encode.optional input____.communityId ), ( "date", (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecDate) |> Encode.optional input____.date ), ( "direction", encodeTransferDirection |> Encode.optional input____.direction ) ]


buildTransferSucceedInput :
    TransferSucceedInputRequiredFields
    -> TransferSucceedInput
buildTransferSucceedInput required____ =
    { from = required____.from, symbol = required____.symbol, to = required____.to }


type alias TransferSucceedInputRequiredFields =
    { from : String
    , symbol : String
    , to : String
    }


{-| Type for the TransferSucceedInput input object.
-}
type alias TransferSucceedInput =
    { from : String
    , symbol : String
    , to : String
    }


{-| Encode a TransferSucceedInput into a value that can be used as an argument.
-}
encodeTransferSucceedInput : TransferSucceedInput -> Value
encodeTransferSucceedInput input____ =
    Encode.maybeObject
        [ ( "from", Encode.string input____.from |> Just ), ( "symbol", Encode.string input____.symbol |> Just ), ( "to", Encode.string input____.to |> Just ) ]


buildUnreadNotificationsSubscriptionInput :
    UnreadNotificationsSubscriptionInputRequiredFields
    -> UnreadNotificationsSubscriptionInput
buildUnreadNotificationsSubscriptionInput required____ =
    { account = required____.account }


type alias UnreadNotificationsSubscriptionInputRequiredFields =
    { account : String }


{-| Type for the UnreadNotificationsSubscriptionInput input object.
-}
type alias UnreadNotificationsSubscriptionInput =
    { account : String }


{-| Encode a UnreadNotificationsSubscriptionInput into a value that can be used as an argument.
-}
encodeUnreadNotificationsSubscriptionInput : UnreadNotificationsSubscriptionInput -> Value
encodeUnreadNotificationsSubscriptionInput input____ =
    Encode.maybeObject
        [ ( "account", Encode.string input____.account |> Just ) ]


buildUserUpdateInput :
    (UserUpdateInputOptionalFields -> UserUpdateInputOptionalFields)
    -> UserUpdateInput
buildUserUpdateInput fillOptionals____ =
    let
        optionals____ =
            fillOptionals____
                { avatar = Absent, bio = Absent, claimNotification = Absent, contacts = Absent, digest = Absent, email = Absent, interests = Absent, location = Absent, name = Absent, transferNotification = Absent }
    in
    { avatar = optionals____.avatar, bio = optionals____.bio, claimNotification = optionals____.claimNotification, contacts = optionals____.contacts, digest = optionals____.digest, email = optionals____.email, interests = optionals____.interests, location = optionals____.location, name = optionals____.name, transferNotification = optionals____.transferNotification }


type alias UserUpdateInputOptionalFields =
    { avatar : OptionalArgument String
    , bio : OptionalArgument String
    , claimNotification : OptionalArgument Bool
    , contacts : OptionalArgument (List ContactInput)
    , digest : OptionalArgument Bool
    , email : OptionalArgument String
    , interests : OptionalArgument String
    , location : OptionalArgument String
    , name : OptionalArgument String
    , transferNotification : OptionalArgument Bool
    }


{-| Type for the UserUpdateInput input object.
-}
type alias UserUpdateInput =
    { avatar : OptionalArgument String
    , bio : OptionalArgument String
    , claimNotification : OptionalArgument Bool
    , contacts : OptionalArgument (List ContactInput)
    , digest : OptionalArgument Bool
    , email : OptionalArgument String
    , interests : OptionalArgument String
    , location : OptionalArgument String
    , name : OptionalArgument String
    , transferNotification : OptionalArgument Bool
    }


{-| Encode a UserUpdateInput into a value that can be used as an argument.
-}
encodeUserUpdateInput : UserUpdateInput -> Value
encodeUserUpdateInput input____ =
    Encode.maybeObject
        [ ( "avatar", Encode.string |> Encode.optional input____.avatar ), ( "bio", Encode.string |> Encode.optional input____.bio ), ( "claimNotification", Encode.bool |> Encode.optional input____.claimNotification ), ( "contacts", (encodeContactInput |> Encode.list) |> Encode.optional input____.contacts ), ( "digest", Encode.bool |> Encode.optional input____.digest ), ( "email", Encode.string |> Encode.optional input____.email ), ( "interests", Encode.string |> Encode.optional input____.interests ), ( "location", Encode.string |> Encode.optional input____.location ), ( "name", Encode.string |> Encode.optional input____.name ), ( "transferNotification", Encode.bool |> Encode.optional input____.transferNotification ) ]
