-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object exposing (..)


type Action
    = Action


type Address
    = Address


type Check
    = Check


type City
    = City


type Claim
    = Claim


type ClaimConnection
    = ClaimConnection


type ClaimEdge
    = ClaimEdge


type Community
    = Community


type CommunityPreview
    = CommunityPreview


type Contact
    = Contact


type Country
    = Country


type DeleteKycAddress
    = DeleteKycAddress


type Exists
    = Exists


type Invite
    = Invite


type KycData
    = KycData


type Mint
    = Mint


type Neighborhood
    = Neighborhood


type Network
    = Network


type NotificationHistory
    = NotificationHistory


type Objective
    = Objective


type Order
    = Order


type PageInfo
    = PageInfo


type Product
    = Product


type PushSubscription
    = PushSubscription


type SearchResult
    = SearchResult


type Session
    = Session


type State
    = State


type Subdomain
    = Subdomain


type Transfer
    = Transfer


type TransferConnection
    = TransferConnection


type TransferEdge
    = TransferEdge


type UnreadNotifications
    = UnreadNotifications


type Upload
    = Upload


type User
    = User
