-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object exposing (..)


type Action
    = Action


type Address
    = Address


type Check
    = Check


type City
    = City


type Claim
    = Claim


type ClaimConnection
    = ClaimConnection


type ClaimEdge
    = ClaimEdge


type Community
    = Community


type Country
    = Country


type DeleteKycAddress
    = DeleteKycAddress


type Invite
    = Invite


type KycData
    = KycData


type Mint
    = Mint


type Neighborhood
    = Neighborhood


type Network
    = Network


type NotificationHistory
    = NotificationHistory


type Objective
    = Objective


type PageInfo
    = PageInfo


type Profile
    = Profile


type PushSubscription
    = PushSubscription


type Sale
    = Sale


type SaleHistory
    = SaleHistory


type SignUp
    = SignUp


type State
    = State


type Transfer
    = Transfer


type TransferConnection
    = TransferConnection


type TransferEdge
    = TransferEdge


type UnreadNotifications
    = UnreadNotifications
