-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Query exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias AnalyzedClaimsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , filter : OptionalArgument Cambiatus.InputObject.ClaimsFilter
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


analyzedClaims :
    (AnalyzedClaimsOptionalArguments -> AnalyzedClaimsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.ClaimConnection
    -> SelectionSet (Maybe decodesTo) RootQuery
analyzedClaims fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, filter = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "filter" filledInOptionals____.filter Cambiatus.InputObject.encodeClaimsFilter, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "analyzedClaims" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias ClaimRequiredArguments =
    { id : Int }


{-| [Auth required] A single claim
-}
claim :
    ClaimRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Claim
    -> SelectionSet decodesTo RootQuery
claim requiredArgs____ object____ =
    Object.selectionForCompositeField "claim" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ Basics.identity


{-| [Auth required] A list of communities in Cambiatus
-}
communities :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet (List decodesTo) RootQuery
communities object____ =
    Object.selectionForCompositeField "communities" [] object____ (Basics.identity >> Decode.list)


type alias CommunityOptionalArguments =
    { subdomain : OptionalArgument String
    , symbol : OptionalArgument String
    }


{-| [Auth required] A single community
-}
community :
    (CommunityOptionalArguments -> CommunityOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet (Maybe decodesTo) RootQuery
community fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { subdomain = Absent, symbol = Absent }

        optionalArgs____ =
            [ Argument.optional "subdomain" filledInOptionals____.subdomain Encode.string, Argument.optional "symbol" filledInOptionals____.symbol Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "community" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias CommunityPreviewOptionalArguments =
    { subdomain : OptionalArgument String
    , symbol : OptionalArgument String
    }


{-| Community Preview, public data available for all communities
-}
communityPreview :
    (CommunityPreviewOptionalArguments -> CommunityPreviewOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.CommunityPreview
    -> SelectionSet (Maybe decodesTo) RootQuery
communityPreview fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { subdomain = Absent, symbol = Absent }

        optionalArgs____ =
            [ Argument.optional "subdomain" filledInOptionals____.subdomain Encode.string, Argument.optional "symbol" filledInOptionals____.symbol Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "communityPreview" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias CountryRequiredArguments =
    { input : Cambiatus.InputObject.CountryInput }


{-| List of supported countries
-}
country :
    CountryRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Country
    -> SelectionSet (Maybe decodesTo) RootQuery
country requiredArgs____ object____ =
    Object.selectionForCompositeField "country" [ Argument.required "input" requiredArgs____.input Cambiatus.InputObject.encodeCountryInput ] object____ (Basics.identity >> Decode.nullable)


type alias DomainAvailableRequiredArguments =
    { domain : String }


{-| [Auth required] Informs if a domain is available or not under Cambiatus
-}
domainAvailable :
    DomainAvailableRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Exists
    -> SelectionSet (Maybe decodesTo) RootQuery
domainAvailable requiredArgs____ object____ =
    Object.selectionForCompositeField "domainAvailable" [ Argument.required "domain" requiredArgs____.domain Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias FetchEncryptedMnemonicRequiredArguments =
    { account : String
    , credentialId : Cambiatus.ScalarCodecs.Id
    }


{-| [Auth required] Fetch the encrypted mnemonic blob for a specific passkey credential
-}
fetchEncryptedMnemonic :
    FetchEncryptedMnemonicRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.EncryptedMnemonicResult
    -> SelectionSet (Maybe decodesTo) RootQuery
fetchEncryptedMnemonic requiredArgs____ object____ =
    Object.selectionForCompositeField "fetchEncryptedMnemonic" [ Argument.required "account" requiredArgs____.account Encode.string, Argument.required "credentialId" requiredArgs____.credentialId (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapEncoder .codecId) ] object____ (Basics.identity >> Decode.nullable)


type alias InviteRequiredArguments =
    { id : String }


{-| An invite
-}
invite :
    InviteRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Invite
    -> SelectionSet (Maybe decodesTo) RootQuery
invite requiredArgs____ object____ =
    Object.selectionForCompositeField "invite" [ Argument.required "id" requiredArgs____.id Encode.string ] object____ (Basics.identity >> Decode.nullable)


type alias NewsRequiredArguments =
    { newsId : Int }


{-| Get news
-}
news :
    NewsRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.News
    -> SelectionSet (Maybe decodesTo) RootQuery
news requiredArgs____ object____ =
    Object.selectionForCompositeField "news" [ Argument.required "newsId" requiredArgs____.newsId Encode.int ] object____ (Basics.identity >> Decode.nullable)


{-| [Auth required] User's notifications
-}
notificationHistory :
    SelectionSet decodesTo Cambiatus.Object.NotificationHistory
    -> SelectionSet (List decodesTo) RootQuery
notificationHistory object____ =
    Object.selectionForCompositeField "notificationHistory" [] object____ (Basics.identity >> Decode.list)


type alias ObjectiveRequiredArguments =
    { id : Int }


{-| [Auth required] A single objective
-}
objective :
    ObjectiveRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Objective
    -> SelectionSet (Maybe decodesTo) RootQuery
objective requiredArgs____ object____ =
    Object.selectionForCompositeField "objective" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias PendingClaimsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , filter : OptionalArgument Cambiatus.InputObject.ClaimsFilter
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| [Auth required] A list of claims
-}
pendingClaims :
    (PendingClaimsOptionalArguments -> PendingClaimsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.ClaimConnection
    -> SelectionSet (Maybe decodesTo) RootQuery
pendingClaims fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, filter = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "filter" filledInOptionals____.filter Cambiatus.InputObject.encodeClaimsFilter, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "pendingClaims" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias ProductRequiredArguments =
    { id : Int }


{-| [Auth required] Gets a single product
-}
product :
    ProductRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Product
    -> SelectionSet (Maybe decodesTo) RootQuery
product requiredArgs____ object____ =
    Object.selectionForCompositeField "product" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProductPreviewRequiredArguments =
    { id : Int }


{-| Public product query, mainly used to preview a sale
-}
productPreview :
    ProductPreviewRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.ProductPreview
    -> SelectionSet decodesTo RootQuery
productPreview requiredArgs____ object____ =
    Object.selectionForCompositeField "productPreview" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ Basics.identity


type alias ProductsOptionalArguments =
    { filters : OptionalArgument Cambiatus.InputObject.ProductsFilterInput }


{-| [Auth required] Products in a community
-}
products :
    (ProductsOptionalArguments -> ProductsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.Product
    -> SelectionSet (List decodesTo) RootQuery
products fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { filters = Absent }

        optionalArgs____ =
            [ Argument.optional "filters" filledInOptionals____.filters Cambiatus.InputObject.encodeProductsFilterInput ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "products" optionalArgs____ object____ (Basics.identity >> Decode.list)


{-| [Auth required] Searches the community for a product or action
-}
search :
    SelectionSet decodesTo Cambiatus.Object.SearchResult
    -> SelectionSet decodesTo RootQuery
search object____ =
    Object.selectionForCompositeField "search" [] object____ Basics.identity


type alias TransferRequiredArguments =
    { id : Int }


{-| [Auth required] A single Transfer
-}
transfer :
    TransferRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.Transfer
    -> SelectionSet (Maybe decodesTo) RootQuery
transfer requiredArgs____ object____ =
    Object.selectionForCompositeField "transfer" [ Argument.required "id" requiredArgs____.id Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias UserRequiredArguments =
    { account : String }


{-| [Auth required] A user
-}
user :
    UserRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet (Maybe decodesTo) RootQuery
user requiredArgs____ object____ =
    Object.selectionForCompositeField "user" [ Argument.required "account" requiredArgs____.account Encode.string ] object____ (Basics.identity >> Decode.nullable)
