-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.ScalarCodecs exposing (..)

import Cambiatus.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    Cambiatus.Scalar.DateTime


type alias Id =
    Cambiatus.Scalar.Id


codecs : Cambiatus.Scalar.Codecs DateTime Id
codecs =
    Cambiatus.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        }
