-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Action exposing (..)

import Cambiatus.Enum.VerificationType
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


claims :
    SelectionSet decodesTo Cambiatus.Object.Claim
    -> SelectionSet (List decodesTo) Cambiatus.Object.Action
claims object_ =
    Object.selectionForCompositeField "claims" [] object_ (identity >> Decode.list)


createdAt : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.Action
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Cambiatus.Object.Action
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Cambiatus.Object.Action
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Cambiatus.Object.Action
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


creator :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Action
creator object_ =
    Object.selectionForCompositeField "creator" [] object_ identity


creatorId : SelectionSet String Cambiatus.Object.Action
creatorId =
    Object.selectionForField "String" "creatorId" [] Decode.string


deadline : SelectionSet (Maybe Cambiatus.ScalarCodecs.DateTime) Cambiatus.Object.Action
deadline =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "deadline" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


description : SelectionSet String Cambiatus.Object.Action
description =
    Object.selectionForField "String" "description" [] Decode.string


hasProofCode : SelectionSet (Maybe Bool) Cambiatus.Object.Action
hasProofCode =
    Object.selectionForField "(Maybe Bool)" "hasProofCode" [] (Decode.bool |> Decode.nullable)


hasProofPhoto : SelectionSet (Maybe Bool) Cambiatus.Object.Action
hasProofPhoto =
    Object.selectionForField "(Maybe Bool)" "hasProofPhoto" [] (Decode.bool |> Decode.nullable)


id : SelectionSet Int Cambiatus.Object.Action
id =
    Object.selectionForField "Int" "id" [] Decode.int


isCompleted : SelectionSet Bool Cambiatus.Object.Action
isCompleted =
    Object.selectionForField "Bool" "isCompleted" [] Decode.bool


objective :
    SelectionSet decodesTo Cambiatus.Object.Objective
    -> SelectionSet decodesTo Cambiatus.Object.Action
objective object_ =
    Object.selectionForCompositeField "objective" [] object_ identity


photoProofInstructions : SelectionSet (Maybe String) Cambiatus.Object.Action
photoProofInstructions =
    Object.selectionForField "(Maybe String)" "photoProofInstructions" [] (Decode.string |> Decode.nullable)


position : SelectionSet (Maybe Int) Cambiatus.Object.Action
position =
    Object.selectionForField "(Maybe Int)" "position" [] (Decode.int |> Decode.nullable)


reward : SelectionSet Float Cambiatus.Object.Action
reward =
    Object.selectionForField "Float" "reward" [] Decode.float


usages : SelectionSet Int Cambiatus.Object.Action
usages =
    Object.selectionForField "Int" "usages" [] Decode.int


usagesLeft : SelectionSet Int Cambiatus.Object.Action
usagesLeft =
    Object.selectionForField "Int" "usagesLeft" [] Decode.int


validators :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet (List decodesTo) Cambiatus.Object.Action
validators object_ =
    Object.selectionForCompositeField "validators" [] object_ (identity >> Decode.list)


verificationType : SelectionSet Cambiatus.Enum.VerificationType.VerificationType Cambiatus.Object.Action
verificationType =
    Object.selectionForField "Enum.VerificationType.VerificationType" "verificationType" [] Cambiatus.Enum.VerificationType.decoder


verifications : SelectionSet Int Cambiatus.Object.Action
verifications =
    Object.selectionForField "Int" "verifications" [] Decode.int


verifierReward : SelectionSet Float Cambiatus.Object.Action
verifierReward =
    Object.selectionForField "Float" "verifierReward" [] Decode.float
