-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Address exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


city :
    SelectionSet decodesTo Cambiatus.Object.City
    -> SelectionSet decodesTo Cambiatus.Object.Address
city object_ =
    Object.selectionForCompositeField "city" [] object_ identity


country :
    SelectionSet decodesTo Cambiatus.Object.Country
    -> SelectionSet decodesTo Cambiatus.Object.Address
country object_ =
    Object.selectionForCompositeField "country" [] object_ identity


neighborhood :
    SelectionSet decodesTo Cambiatus.Object.Neighborhood
    -> SelectionSet decodesTo Cambiatus.Object.Address
neighborhood object_ =
    Object.selectionForCompositeField "neighborhood" [] object_ identity


number : SelectionSet (Maybe String) Cambiatus.Object.Address
number =
    Object.selectionForField "(Maybe String)" "number" [] (Decode.string |> Decode.nullable)


state :
    SelectionSet decodesTo Cambiatus.Object.State
    -> SelectionSet decodesTo Cambiatus.Object.Address
state object_ =
    Object.selectionForCompositeField "state" [] object_ identity


street : SelectionSet String Cambiatus.Object.Address
street =
    Object.selectionForField "String" "street" [] Decode.string


zip : SelectionSet String Cambiatus.Object.Address
zip =
    Object.selectionForField "String" "zip" [] Decode.string
