-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Check exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


claim :
    SelectionSet decodesTo Cambiatus.Object.Claim
    -> SelectionSet decodesTo Cambiatus.Object.Check
claim object_ =
    Object.selectionForCompositeField "claim" [] object_ identity


createdAt : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.Check
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Cambiatus.Object.Check
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Cambiatus.Object.Check
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Cambiatus.Object.Check
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


isVerified : SelectionSet Bool Cambiatus.Object.Check
isVerified =
    Object.selectionForField "Bool" "isVerified" [] Decode.bool


validator :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Check
validator object_ =
    Object.selectionForCompositeField "validator" [] object_ identity
