-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.ClaimerActionHistory exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


approved : SelectionSet Int Cambiatus.Object.ClaimerActionHistory
approved =
    Object.selectionForField "Int" "approved" [] Decode.int


pending : SelectionSet Int Cambiatus.Object.ClaimerActionHistory
pending =
    Object.selectionForField "Int" "pending" [] Decode.int


rejected : SelectionSet Int Cambiatus.Object.ClaimerActionHistory
rejected =
    Object.selectionForField "Int" "rejected" [] Decode.int


total : SelectionSet Int Cambiatus.Object.ClaimerActionHistory
total =
    Object.selectionForField "Int" "total" [] Decode.int
