-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Contact exposing (..)

import Cambiatus.Enum.ContactType
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


externalId : SelectionSet (Maybe String) Cambiatus.Object.Contact
externalId =
    Object.selectionForField "(Maybe String)" "externalId" [] (Decode.string |> Decode.nullable)


type_ : SelectionSet (Maybe Cambiatus.Enum.ContactType.ContactType) Cambiatus.Object.Contact
type_ =
    Object.selectionForField "(Maybe Enum.ContactType.ContactType)" "type" [] (Cambiatus.Enum.ContactType.decoder |> Decode.nullable)
