-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Contribution exposing (..)

import Cambiatus.Enum.ContributionStatusType
import Cambiatus.Enum.CurrencyType
import Cambiatus.Enum.PaymentMethodType
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet Float Cambiatus.Object.Contribution
amount =
    Object.selectionForField "Float" "amount" [] Decode.float


community :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet decodesTo Cambiatus.Object.Contribution
community object_ =
    Object.selectionForCompositeField "community" [] object_ identity


currency : SelectionSet Cambiatus.Enum.CurrencyType.CurrencyType Cambiatus.Object.Contribution
currency =
    Object.selectionForField "Enum.CurrencyType.CurrencyType" "currency" [] Cambiatus.Enum.CurrencyType.decoder


id : SelectionSet String Cambiatus.Object.Contribution
id =
    Object.selectionForField "String" "id" [] Decode.string


insertedAt : SelectionSet Cambiatus.ScalarCodecs.NaiveDateTime Cambiatus.Object.Contribution
insertedAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "insertedAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


paymentMethod : SelectionSet Cambiatus.Enum.PaymentMethodType.PaymentMethodType Cambiatus.Object.Contribution
paymentMethod =
    Object.selectionForField "Enum.PaymentMethodType.PaymentMethodType" "paymentMethod" [] Cambiatus.Enum.PaymentMethodType.decoder


status : SelectionSet Cambiatus.Enum.ContributionStatusType.ContributionStatusType Cambiatus.Object.Contribution
status =
    Object.selectionForField "Enum.ContributionStatusType.ContributionStatusType" "status" [] Cambiatus.Enum.ContributionStatusType.decoder


updatedAt : SelectionSet Cambiatus.ScalarCodecs.NaiveDateTime Cambiatus.Object.Contribution
updatedAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "updatedAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


user :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Contribution
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity
