-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.DeleteKyc exposing (..)

import Cambiatus.Enum.DeleteKycStatus
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


reason : SelectionSet String Cambiatus.Object.DeleteKyc
reason =
    Object.selectionForField "String" "reason" [] Decode.string


status : SelectionSet Cambiatus.Enum.DeleteKycStatus.DeleteKycStatus Cambiatus.Object.DeleteKyc
status =
    Object.selectionForField "Enum.DeleteKycStatus.DeleteKycStatus" "status" [] Cambiatus.Enum.DeleteKycStatus.decoder
