-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.KycData exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


country :
    SelectionSet decodesTo Cambiatus.Object.Country
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.KycData
country object_ =
    Object.selectionForCompositeField "country" [] object_ (identity >> Decode.nullable)


document : SelectionSet String Cambiatus.Object.KycData
document =
    Object.selectionForField "String" "document" [] Decode.string


documentType : SelectionSet String Cambiatus.Object.KycData
documentType =
    Object.selectionForField "String" "documentType" [] Decode.string


isVerified : SelectionSet Bool Cambiatus.Object.KycData
isVerified =
    Object.selectionForField "Bool" "isVerified" [] Decode.bool


phone : SelectionSet String Cambiatus.Object.KycData
phone =
    Object.selectionForField "String" "phone" [] Decode.string


userType : SelectionSet String Cambiatus.Object.KycData
userType =
    Object.selectionForField "String" "userType" [] Decode.string
