-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Network exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


account :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.Network
account object_ =
    Object.selectionForCompositeField "account" [] object_ (identity >> Decode.nullable)


community :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.Network
community object_ =
    Object.selectionForCompositeField "community" [] object_ (identity >> Decode.nullable)


createdAt : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.Network
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Cambiatus.Object.Network
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Cambiatus.Object.Network
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Cambiatus.Object.Network
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


invitedBy : SelectionSet (Maybe String) Cambiatus.Object.Network
invitedBy =
    Object.selectionForField "(Maybe String)" "invitedBy" [] (Decode.string |> Decode.nullable)
