-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.News exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


description : SelectionSet String Cambiatus.Object.News
description =
    Object.selectionForField "String" "description" [] Decode.string


id : SelectionSet Int Cambiatus.Object.News
id =
    Object.selectionForField "Int" "id" [] Decode.int


insertedAt : SelectionSet Cambiatus.ScalarCodecs.NaiveDateTime Cambiatus.Object.News
insertedAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "insertedAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


reactions :
    SelectionSet decodesTo Cambiatus.Object.ReactionType
    -> SelectionSet (List decodesTo) Cambiatus.Object.News
reactions object_ =
    Object.selectionForCompositeField "reactions" [] object_ (identity >> Decode.list)


receipt :
    SelectionSet decodesTo Cambiatus.Object.NewsReceipt
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.News
receipt object_ =
    Object.selectionForCompositeField "receipt" [] object_ (identity >> Decode.nullable)


scheduling : SelectionSet (Maybe Cambiatus.ScalarCodecs.DateTime) Cambiatus.Object.News
scheduling =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "scheduling" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


title : SelectionSet String Cambiatus.Object.News
title =
    Object.selectionForField "String" "title" [] Decode.string


updatedAt : SelectionSet Cambiatus.ScalarCodecs.NaiveDateTime Cambiatus.Object.News
updatedAt =
    Object.selectionForField "ScalarCodecs.NaiveDateTime" "updatedAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder)


user :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.News
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


versions :
    SelectionSet decodesTo Cambiatus.Object.NewsVersion
    -> SelectionSet (List decodesTo) Cambiatus.Object.News
versions object_ =
    Object.selectionForCompositeField "versions" [] object_ (identity >> Decode.list)
