-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Objective exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias ActionsOptionalArguments =
    { input : OptionalArgument Cambiatus.InputObject.ActionsInput }


actions :
    (ActionsOptionalArguments -> ActionsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.Action
    -> SelectionSet (List decodesTo) Cambiatus.Object.Objective
actions fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { input = Absent }

        optionalArgs =
            [ Argument.optional "input" filledInOptionals.input Cambiatus.InputObject.encodeActionsInput ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "actions" optionalArgs object_ (identity >> Decode.list)


community :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet decodesTo Cambiatus.Object.Objective
community object_ =
    Object.selectionForCompositeField "community" [] object_ identity


completedAt : SelectionSet (Maybe Cambiatus.ScalarCodecs.NaiveDateTime) Cambiatus.Object.Objective
completedAt =
    Object.selectionForField "(Maybe ScalarCodecs.NaiveDateTime)" "completedAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder |> Decode.nullable)


createdAt : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.Objective
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Cambiatus.Object.Objective
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Cambiatus.Object.Objective
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Cambiatus.Object.Objective
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


creator :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Objective
creator object_ =
    Object.selectionForCompositeField "creator" [] object_ identity


creatorId : SelectionSet String Cambiatus.Object.Objective
creatorId =
    Object.selectionForField "String" "creatorId" [] Decode.string


description : SelectionSet String Cambiatus.Object.Objective
description =
    Object.selectionForField "String" "description" [] Decode.string


id : SelectionSet Int Cambiatus.Object.Objective
id =
    Object.selectionForField "Int" "id" [] Decode.int


isCompleted : SelectionSet Bool Cambiatus.Object.Objective
isCompleted =
    Object.selectionForField "Bool" "isCompleted" [] Decode.bool
