-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Order exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet Float Cambiatus.Object.Order
amount =
    Object.selectionForField "Float" "amount" [] Decode.float


createdAt : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.Order
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Cambiatus.Object.Order
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Cambiatus.Object.Order
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Cambiatus.Object.Order
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


from :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Order
from object_ =
    Object.selectionForCompositeField "from" [] object_ identity


fromId : SelectionSet String Cambiatus.Object.Order
fromId =
    Object.selectionForField "String" "fromId" [] Decode.string


id : SelectionSet Int Cambiatus.Object.Order
id =
    Object.selectionForField "Int" "id" [] Decode.int


product :
    SelectionSet decodesTo Cambiatus.Object.Product
    -> SelectionSet decodesTo Cambiatus.Object.Order
product object_ =
    Object.selectionForCompositeField "product" [] object_ identity


productId : SelectionSet Int Cambiatus.Object.Order
productId =
    Object.selectionForField "Int" "productId" [] Decode.int


to :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Order
to object_ =
    Object.selectionForCompositeField "to" [] object_ identity


toId : SelectionSet String Cambiatus.Object.Order
toId =
    Object.selectionForField "String" "toId" [] Decode.string


units : SelectionSet (Maybe Int) Cambiatus.Object.Order
units =
    Object.selectionForField "(Maybe Int)" "units" [] (Decode.int |> Decode.nullable)
