-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.ProductPreview exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


community :
    SelectionSet decodesTo Cambiatus.Object.CommunityPreview
    -> SelectionSet decodesTo Cambiatus.Object.ProductPreview
community object_ =
    Object.selectionForCompositeField "community" [] object_ identity


communityId : SelectionSet String Cambiatus.Object.ProductPreview
communityId =
    Object.selectionForField "String" "communityId" [] Decode.string


creatorId : SelectionSet String Cambiatus.Object.ProductPreview
creatorId =
    Object.selectionForField "String" "creatorId" [] Decode.string


description : SelectionSet String Cambiatus.Object.ProductPreview
description =
    Object.selectionForField "String" "description" [] Decode.string


id : SelectionSet Int Cambiatus.Object.ProductPreview
id =
    Object.selectionForField "Int" "id" [] Decode.int


images :
    SelectionSet decodesTo Cambiatus.Object.ProductImage
    -> SelectionSet (List decodesTo) Cambiatus.Object.ProductPreview
images object_ =
    Object.selectionForCompositeField "images" [] object_ (identity >> Decode.list)


price : SelectionSet Float Cambiatus.Object.ProductPreview
price =
    Object.selectionForField "Float" "price" [] Decode.float


title : SelectionSet String Cambiatus.Object.ProductPreview
title =
    Object.selectionForField "String" "title" [] Decode.string
