-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.PushSubscription exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


accountId : SelectionSet (Maybe String) Cambiatus.Object.PushSubscription
accountId =
    Object.selectionForField "(Maybe String)" "accountId" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Cambiatus.ScalarCodecs.Id) Cambiatus.Object.PushSubscription
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)
