-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Reward exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


action :
    SelectionSet decodesTo Cambiatus.Object.Action
    -> SelectionSet decodesTo Cambiatus.Object.Reward
action object____ =
    Object.selectionForCompositeField "action" [] object____ Basics.identity


receiver :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet decodesTo Cambiatus.Object.Reward
receiver object____ =
    Object.selectionForCompositeField "receiver" [] object____ Basics.identity
