-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.Role exposing (..)

import Cambiatus.Enum.Permission
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


color : SelectionSet (Maybe String) Cambiatus.Object.Role
color =
    Object.selectionForField "(Maybe String)" "color" [] (Decode.string |> Decode.nullable)


name : SelectionSet String Cambiatus.Object.Role
name =
    Object.selectionForField "String" "name" [] Decode.string


permissions : SelectionSet (List Cambiatus.Enum.Permission.Permission) Cambiatus.Object.Role
permissions =
    Object.selectionForField "(List Enum.Permission.Permission)" "permissions" [] (Cambiatus.Enum.Permission.decoder |> Decode.list)
