-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.SaleHistory exposing (..)

import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet Float Cambiatus.Object.SaleHistory
amount =
    Object.selectionForField "Float" "amount" [] Decode.float


community :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet decodesTo Cambiatus.Object.SaleHistory
community object_ =
    Object.selectionForCompositeField "community" [] object_ identity


communityId : SelectionSet String Cambiatus.Object.SaleHistory
communityId =
    Object.selectionForField "String" "communityId" [] Decode.string


from :
    SelectionSet decodesTo Cambiatus.Object.Profile
    -> SelectionSet decodesTo Cambiatus.Object.SaleHistory
from object_ =
    Object.selectionForCompositeField "from" [] object_ identity


fromId : SelectionSet String Cambiatus.Object.SaleHistory
fromId =
    Object.selectionForField "String" "fromId" [] Decode.string


id : SelectionSet Int Cambiatus.Object.SaleHistory
id =
    Object.selectionForField "Int" "id" [] Decode.int


sale :
    SelectionSet decodesTo Cambiatus.Object.Sale
    -> SelectionSet decodesTo Cambiatus.Object.SaleHistory
sale object_ =
    Object.selectionForCompositeField "sale" [] object_ identity


saleId : SelectionSet Int Cambiatus.Object.SaleHistory
saleId =
    Object.selectionForField "Int" "saleId" [] Decode.int


to :
    SelectionSet decodesTo Cambiatus.Object.Profile
    -> SelectionSet decodesTo Cambiatus.Object.SaleHistory
to object_ =
    Object.selectionForCompositeField "to" [] object_ identity


toId : SelectionSet String Cambiatus.Object.SaleHistory
toId =
    Object.selectionForField "String" "toId" [] Decode.string


units : SelectionSet (Maybe Int) Cambiatus.Object.SaleHistory
units =
    Object.selectionForField "(Maybe Int)" "units" [] (Decode.int |> Decode.nullable)
