-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.SignUpResponse exposing (..)

import Cambiatus.Enum.SignUpStatus
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


reason : SelectionSet (Maybe String) Cambiatus.Object.SignUpResponse
reason =
    Object.selectionForField "(Maybe String)" "reason" [] (Decode.string |> Decode.nullable)


status : SelectionSet Cambiatus.Enum.SignUpStatus.SignUpStatus Cambiatus.Object.SignUpResponse
status =
    Object.selectionForField "Enum.SignUpStatus.SignUpStatus" "status" [] Cambiatus.Enum.SignUpStatus.decoder


user :
    SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.SignUpResponse
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)
