-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Object.User exposing (..)

import Cambiatus.Enum.ContributionStatusType
import Cambiatus.Enum.Language
import Cambiatus.InputObject
import Cambiatus.Interface
import Cambiatus.Object
import Cambiatus.Scalar
import Cambiatus.ScalarCodecs
import Cambiatus.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


account : SelectionSet String Cambiatus.Object.User
account =
    Object.selectionForField "String" "account" [] Decode.string


address :
    SelectionSet decodesTo Cambiatus.Object.Address
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.User
address object____ =
    Object.selectionForCompositeField "address" [] object____ (Basics.identity >> Decode.nullable)


analysisCount : SelectionSet Int Cambiatus.Object.User
analysisCount =
    Object.selectionForField "Int" "analysisCount" [] Decode.int


avatar : SelectionSet (Maybe String) Cambiatus.Object.User
avatar =
    Object.selectionForField "(Maybe String)" "avatar" [] (Decode.string |> Decode.nullable)


bio : SelectionSet (Maybe String) Cambiatus.Object.User
bio =
    Object.selectionForField "(Maybe String)" "bio" [] (Decode.string |> Decode.nullable)


chatToken : SelectionSet (Maybe String) Cambiatus.Object.User
chatToken =
    Object.selectionForField "(Maybe String)" "chatToken" [] (Decode.string |> Decode.nullable)


chatUserId : SelectionSet (Maybe String) Cambiatus.Object.User
chatUserId =
    Object.selectionForField "(Maybe String)" "chatUserId" [] (Decode.string |> Decode.nullable)


claimNotification : SelectionSet Bool Cambiatus.Object.User
claimNotification =
    Object.selectionForField "Bool" "claimNotification" [] Decode.bool


type alias ClaimsOptionalArguments =
    { communityId : OptionalArgument String }


{-|

  - communityId - Optional community filter, filling this will get only claims from this community

-}
claims :
    (ClaimsOptionalArguments -> ClaimsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.Claim
    -> SelectionSet (List decodesTo) Cambiatus.Object.User
claims fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { communityId = Absent }

        optionalArgs____ =
            [ Argument.optional "communityId" filledInOptionals____.communityId Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "claims" optionalArgs____ object____ (Basics.identity >> Decode.list)


communities :
    SelectionSet decodesTo Cambiatus.Object.Community
    -> SelectionSet (List decodesTo) Cambiatus.Object.User
communities object____ =
    Object.selectionForCompositeField "communities" [] object____ (Basics.identity >> Decode.list)


contacts :
    SelectionSet decodesTo Cambiatus.Object.Contact
    -> SelectionSet (List decodesTo) Cambiatus.Object.User
contacts object____ =
    Object.selectionForCompositeField "contacts" [] object____ (Basics.identity >> Decode.list)


type alias ContributionCountOptionalArguments =
    { communityId : OptionalArgument String }


{-|

  - communityId - Optional community filter, filling this will get only contributions from this community

-}
contributionCount :
    (ContributionCountOptionalArguments -> ContributionCountOptionalArguments)
    -> SelectionSet Int Cambiatus.Object.User
contributionCount fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { communityId = Absent }

        optionalArgs____ =
            [ Argument.optional "communityId" filledInOptionals____.communityId Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "Int" "contributionCount" optionalArgs____ Decode.int


type alias ContributionsOptionalArguments =
    { communityId : OptionalArgument String
    , status : OptionalArgument Cambiatus.Enum.ContributionStatusType.ContributionStatusType
    }


contributions :
    (ContributionsOptionalArguments -> ContributionsOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.Contribution
    -> SelectionSet (List decodesTo) Cambiatus.Object.User
contributions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { communityId = Absent, status = Absent }

        optionalArgs____ =
            [ Argument.optional "communityId" filledInOptionals____.communityId Encode.string, Argument.optional "status" filledInOptionals____.status (Encode.enum Cambiatus.Enum.ContributionStatusType.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "contributions" optionalArgs____ object____ (Basics.identity >> Decode.list)


createdAt : SelectionSet (Maybe String) Cambiatus.Object.User
createdAt =
    Object.selectionForField "(Maybe String)" "createdAt" [] (Decode.string |> Decode.nullable)


createdBlock : SelectionSet (Maybe Int) Cambiatus.Object.User
createdBlock =
    Object.selectionForField "(Maybe Int)" "createdBlock" [] (Decode.int |> Decode.nullable)


createdEosAccount : SelectionSet (Maybe String) Cambiatus.Object.User
createdEosAccount =
    Object.selectionForField "(Maybe String)" "createdEosAccount" [] (Decode.string |> Decode.nullable)


digest : SelectionSet Bool Cambiatus.Object.User
digest =
    Object.selectionForField "Bool" "digest" [] Decode.bool


email : SelectionSet (Maybe String) Cambiatus.Object.User
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


type alias GetPayersByAccountRequiredArguments =
    { account : String }


{-| List of payers to the given recipient fetched by the part of the account name.
-}
getPayersByAccount :
    GetPayersByAccountRequiredArguments
    -> SelectionSet decodesTo Cambiatus.Object.User
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Cambiatus.Object.User
getPayersByAccount requiredArgs____ object____ =
    Object.selectionForCompositeField "getPayersByAccount" [ Argument.required "account" requiredArgs____.account Encode.string ] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


interests : SelectionSet (Maybe String) Cambiatus.Object.User
interests =
    Object.selectionForField "(Maybe String)" "interests" [] (Decode.string |> Decode.nullable)


kyc :
    SelectionSet decodesTo Cambiatus.Object.KycData
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.User
kyc object____ =
    Object.selectionForCompositeField "kyc" [] object____ (Basics.identity >> Decode.nullable)


language : SelectionSet (Maybe Cambiatus.Enum.Language.Language) Cambiatus.Object.User
language =
    Object.selectionForField "(Maybe Enum.Language.Language)" "language" [] (Cambiatus.Enum.Language.decoder |> Decode.nullable)


lastSeen : SelectionSet (Maybe Cambiatus.ScalarCodecs.DateTime) Cambiatus.Object.User
lastSeen =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "lastSeen" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


latestAcceptedTerms : SelectionSet (Maybe Cambiatus.ScalarCodecs.NaiveDateTime) Cambiatus.Object.User
latestAcceptedTerms =
    Object.selectionForField "(Maybe ScalarCodecs.NaiveDateTime)" "latestAcceptedTerms" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecNaiveDateTime |> .decoder |> Decode.nullable)


location : SelectionSet (Maybe String) Cambiatus.Object.User
location =
    Object.selectionForField "(Maybe String)" "location" [] (Decode.string |> Decode.nullable)


memberSince : SelectionSet Cambiatus.ScalarCodecs.DateTime Cambiatus.Object.User
memberSince =
    Object.selectionForField "ScalarCodecs.DateTime" "memberSince" [] (Cambiatus.ScalarCodecs.codecs |> Cambiatus.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


name : SelectionSet (Maybe String) Cambiatus.Object.User
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


network :
    SelectionSet decodesTo Cambiatus.Object.Network
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Cambiatus.Object.User
network object____ =
    Object.selectionForCompositeField "network" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


products :
    SelectionSet decodesTo Cambiatus.Object.Product
    -> SelectionSet (List (Maybe decodesTo)) Cambiatus.Object.User
products object____ =
    Object.selectionForCompositeField "products" [] object____ (Basics.identity >> Decode.nullable >> Decode.list)


roles :
    SelectionSet decodesTo Cambiatus.Object.Role
    -> SelectionSet (List decodesTo) Cambiatus.Object.User
roles object____ =
    Object.selectionForCompositeField "roles" [] object____ (Basics.identity >> Decode.list)


transferNotification : SelectionSet Bool Cambiatus.Object.User
transferNotification =
    Object.selectionForField "Bool" "transferNotification" [] Decode.bool


type alias TransfersOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , filter : OptionalArgument Cambiatus.InputObject.TransferFilter
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-|

  - filter - Optional Filters for querying transfers

-}
transfers :
    (TransfersOptionalArguments -> TransfersOptionalArguments)
    -> SelectionSet decodesTo Cambiatus.Object.TransferConnection
    -> SelectionSet (Maybe decodesTo) Cambiatus.Object.User
transfers fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, filter = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "filter" filledInOptionals____.filter Cambiatus.InputObject.encodeTransferFilter, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "transfers" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
