-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object exposing (..)


type Action
    = Action


type ChatPreferences
    = ChatPreferences


type Check
    = Check


type Claim
    = Claim


type Community
    = Community


type Network
    = Network


type Objective
    = Objective


type PageInfo
    = PageInfo


type Profile
    = Profile


type PushSubscription
    = PushSubscription


type Sale
    = Sale


type SaleHistory
    = SaleHistory


type Transfer
    = Transfer


type TransferConnection
    = TransferConnection


type TransferEdge
    = TransferEdge


type Validator
    = Validator
