-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.ScalarCodecs exposing (DateTime, Id, codecs)

import Bespiral.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    Bespiral.Scalar.DateTime


type alias Id =
    Bespiral.Scalar.Id


codecs : Bespiral.Scalar.Codecs DateTime Id
codecs =
    Bespiral.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        }
