-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object.Action exposing (..)

import Bespiral.Enum.VerificationType
import Bespiral.InputObject
import Bespiral.Interface
import Bespiral.Object
import Bespiral.Scalar
import Bespiral.ScalarCodecs
import Bespiral.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


claims : SelectionSet decodesTo Bespiral.Object.Claim -> SelectionSet (List decodesTo) Bespiral.Object.Action
claims object_ =
    Object.selectionForCompositeField "claims" [] object_ (identity >> Decode.list)


createdAt : SelectionSet Bespiral.ScalarCodecs.DateTime Bespiral.Object.Action
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Bespiral.ScalarCodecs.codecs |> Bespiral.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Bespiral.Object.Action
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Bespiral.Object.Action
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Bespiral.Object.Action
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


creator : SelectionSet decodesTo Bespiral.Object.Profile -> SelectionSet decodesTo Bespiral.Object.Action
creator object_ =
    Object.selectionForCompositeField "creator" [] object_ identity


creatorId : SelectionSet String Bespiral.Object.Action
creatorId =
    Object.selectionForField "String" "creatorId" [] Decode.string


deadline : SelectionSet (Maybe Bespiral.ScalarCodecs.DateTime) Bespiral.Object.Action
deadline =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "deadline" [] (Bespiral.ScalarCodecs.codecs |> Bespiral.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


description : SelectionSet String Bespiral.Object.Action
description =
    Object.selectionForField "String" "description" [] Decode.string


id : SelectionSet Int Bespiral.Object.Action
id =
    Object.selectionForField "Int" "id" [] Decode.int


isCompleted : SelectionSet Bool Bespiral.Object.Action
isCompleted =
    Object.selectionForField "Bool" "isCompleted" [] Decode.bool


objective : SelectionSet decodesTo Bespiral.Object.Objective -> SelectionSet decodesTo Bespiral.Object.Action
objective object_ =
    Object.selectionForCompositeField "objective" [] object_ identity


reward : SelectionSet Float Bespiral.Object.Action
reward =
    Object.selectionForField "Float" "reward" [] Decode.float


usages : SelectionSet Int Bespiral.Object.Action
usages =
    Object.selectionForField "Int" "usages" [] Decode.int


usagesLeft : SelectionSet Int Bespiral.Object.Action
usagesLeft =
    Object.selectionForField "Int" "usagesLeft" [] Decode.int


validators : SelectionSet decodesTo Bespiral.Object.Validator -> SelectionSet (List decodesTo) Bespiral.Object.Action
validators object_ =
    Object.selectionForCompositeField "validators" [] object_ (identity >> Decode.list)


verificationType : SelectionSet Bespiral.Enum.VerificationType.VerificationType Bespiral.Object.Action
verificationType =
    Object.selectionForField "Enum.VerificationType.VerificationType" "verificationType" [] Bespiral.Enum.VerificationType.decoder


verifications : SelectionSet Int Bespiral.Object.Action
verifications =
    Object.selectionForField "Int" "verifications" [] Decode.int


verifierReward : SelectionSet Float Bespiral.Object.Action
verifierReward =
    Object.selectionForField "Float" "verifierReward" [] Decode.float
