-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object.Check exposing (claim, createdAt, createdBlock, createdEosAccount, createdTx, isVerified, validator)

import Bespiral.InputObject
import Bespiral.Interface
import Bespiral.Object
import Bespiral.Scalar
import Bespiral.ScalarCodecs
import Bespiral.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


claim : SelectionSet decodesTo Bespiral.Object.Claim -> SelectionSet decodesTo Bespiral.Object.Check
claim object_ =
    Object.selectionForCompositeField "claim" [] object_ identity


createdAt : SelectionSet Bespiral.ScalarCodecs.DateTime Bespiral.Object.Check
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Bespiral.ScalarCodecs.codecs |> Bespiral.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Bespiral.Object.Check
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Bespiral.Object.Check
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Bespiral.Object.Check
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


isVerified : SelectionSet Bool Bespiral.Object.Check
isVerified =
    Object.selectionForField "Bool" "isVerified" [] Decode.bool


validator : SelectionSet decodesTo Bespiral.Object.Profile -> SelectionSet decodesTo Bespiral.Object.Check
validator object_ =
    Object.selectionForCompositeField "validator" [] object_ identity
