-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object.Claim exposing (ChecksOptionalArguments, action, checks, claimer, createdAt, createdBlock, createdEosAccount, createdTx, id, isVerified)

import Bespiral.InputObject
import Bespiral.Interface
import Bespiral.Object
import Bespiral.Scalar
import Bespiral.ScalarCodecs
import Bespiral.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


action : SelectionSet decodesTo Bespiral.Object.Action -> SelectionSet decodesTo Bespiral.Object.Claim
action object_ =
    Object.selectionForCompositeField "action" [] object_ identity


type alias ChecksOptionalArguments =
    { input : OptionalArgument Bespiral.InputObject.ChecksInput }


checks : (ChecksOptionalArguments -> ChecksOptionalArguments) -> SelectionSet decodesTo Bespiral.Object.Check -> SelectionSet (List decodesTo) Bespiral.Object.Claim
checks fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { input = Absent }

        optionalArgs =
            [ Argument.optional "input" filledInOptionals.input Bespiral.InputObject.encodeChecksInput ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "checks" optionalArgs object_ (identity >> Decode.list)


claimer : SelectionSet decodesTo Bespiral.Object.Profile -> SelectionSet decodesTo Bespiral.Object.Claim
claimer object_ =
    Object.selectionForCompositeField "claimer" [] object_ identity


createdAt : SelectionSet Bespiral.ScalarCodecs.DateTime Bespiral.Object.Claim
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Bespiral.ScalarCodecs.codecs |> Bespiral.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


createdBlock : SelectionSet Int Bespiral.Object.Claim
createdBlock =
    Object.selectionForField "Int" "createdBlock" [] Decode.int


createdEosAccount : SelectionSet String Bespiral.Object.Claim
createdEosAccount =
    Object.selectionForField "String" "createdEosAccount" [] Decode.string


createdTx : SelectionSet String Bespiral.Object.Claim
createdTx =
    Object.selectionForField "String" "createdTx" [] Decode.string


id : SelectionSet Int Bespiral.Object.Claim
id =
    Object.selectionForField "Int" "id" [] Decode.int


isVerified : SelectionSet Bool Bespiral.Object.Claim
isVerified =
    Object.selectionForField "Bool" "isVerified" [] Decode.bool
