-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object.PushSubscription exposing (..)

import Bespiral.InputObject
import Bespiral.Interface
import Bespiral.Object
import Bespiral.Scalar
import Bespiral.ScalarCodecs
import Bespiral.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


accountId : SelectionSet (Maybe String) Bespiral.Object.PushSubscription
accountId =
    Object.selectionForField "(Maybe String)" "accountId" [] (Decode.string |> Decode.nullable)


id : SelectionSet (Maybe Bespiral.ScalarCodecs.Id) Bespiral.Object.PushSubscription
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (Bespiral.ScalarCodecs.codecs |> Bespiral.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)
