-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bespiral.Object.SaleHistory exposing (..)

import Bespiral.InputObject
import Bespiral.Interface
import Bespiral.Object
import Bespiral.Scalar
import Bespiral.ScalarCodecs
import Bespiral.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


amount : SelectionSet Float Bespiral.Object.SaleHistory
amount =
    Object.selectionForField "Float" "amount" [] Decode.float


community : SelectionSet decodesTo Bespiral.Object.Community -> SelectionSet decodesTo Bespiral.Object.SaleHistory
community object_ =
    Object.selectionForCompositeField "community" [] object_ identity


communityId : SelectionSet String Bespiral.Object.SaleHistory
communityId =
    Object.selectionForField "String" "communityId" [] Decode.string


from : SelectionSet decodesTo Bespiral.Object.Profile -> SelectionSet decodesTo Bespiral.Object.SaleHistory
from object_ =
    Object.selectionForCompositeField "from" [] object_ identity


fromId : SelectionSet String Bespiral.Object.SaleHistory
fromId =
    Object.selectionForField "String" "fromId" [] Decode.string


id : SelectionSet Int Bespiral.Object.SaleHistory
id =
    Object.selectionForField "Int" "id" [] Decode.int


sale : SelectionSet decodesTo Bespiral.Object.Sale -> SelectionSet decodesTo Bespiral.Object.SaleHistory
sale object_ =
    Object.selectionForCompositeField "sale" [] object_ identity


saleId : SelectionSet Int Bespiral.Object.SaleHistory
saleId =
    Object.selectionForField "Int" "saleId" [] Decode.int


to : SelectionSet decodesTo Bespiral.Object.Profile -> SelectionSet decodesTo Bespiral.Object.SaleHistory
to object_ =
    Object.selectionForCompositeField "to" [] object_ identity


toId : SelectionSet String Bespiral.Object.SaleHistory
toId =
    Object.selectionForField "String" "toId" [] Decode.string


units : SelectionSet (Maybe Int) Bespiral.Object.SaleHistory
units =
    Object.selectionForField "(Maybe Int)" "units" [] (Decode.int |> Decode.nullable)
