window._env_ = {
  CHAIN_URL: %CHAIN_URL,
  CHAIN_PORT: %CHAIN_PORT,
  CHAIN_ID: %CHAIN_ID,
  API_URL: %API_URL,
  GRAPHQL_URL: %GRAPHQL_URL,
  CHAT_URL: %CHAT_URL,
  IPFS_URL: %IPFS_URL,
  PUSH_KEY: %PUSH_KEY,
  LOGO: %LOGO
}
