-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Enum.ContributionStatusType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Approved - Approved by the external processor
  - Captured - Captured / Received by the external processor
  - Created - Created successfully
  - Failed - Failed
  - Rejected - Rejected by the external processor

-}
type ContributionStatusType
    = Approved
    | Captured
    | Created
    | Failed
    | Rejected


list : List ContributionStatusType
list =
    [ Approved, Captured, Created, Failed, Rejected ]


decoder : Decoder ContributionStatusType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "APPROVED" ->
                        Decode.succeed Approved

                    "CAPTURED" ->
                        Decode.succeed Captured

                    "CREATED" ->
                        Decode.succeed Created

                    "FAILED" ->
                        Decode.succeed Failed

                    "REJECTED" ->
                        Decode.succeed Rejected

                    _ ->
                        Decode.fail ("Invalid ContributionStatusType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : ContributionStatusType -> String
toString enum =
    case enum of
        Approved ->
            "APPROVED"

        Captured ->
            "CAPTURED"

        Created ->
            "CREATED"

        Failed ->
            "FAILED"

        Rejected ->
            "REJECTED"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ContributionStatusType
fromString enumString =
    case enumString of
        "APPROVED" ->
            Just Approved

        "CAPTURED" ->
            Just Captured

        "CREATED" ->
            Just Created

        "FAILED" ->
            Just Failed

        "REJECTED" ->
            Just Rejected

        _ ->
            Nothing
