-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Enum.PaymentMethodType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Bitcoin - Bitcoin Mainnet
  - Eos - EOS Mainnet
  - Ethereum - Ethereum Mainnet
  - Paypal - Paypal, used to process FIAT

-}
type PaymentMethodType
    = Bitcoin
    | Eos
    | Ethereum
    | Paypal


list : List PaymentMethodType
list =
    [ Bitcoin, Eos, Ethereum, Paypal ]


decoder : Decoder PaymentMethodType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "BITCOIN" ->
                        Decode.succeed Bitcoin

                    "EOS" ->
                        Decode.succeed Eos

                    "ETHEREUM" ->
                        Decode.succeed Ethereum

                    "PAYPAL" ->
                        Decode.succeed Paypal

                    _ ->
                        Decode.fail ("Invalid PaymentMethodType type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : PaymentMethodType -> String
toString enum =
    case enum of
        Bitcoin ->
            "BITCOIN"

        Eos ->
            "EOS"

        Ethereum ->
            "ETHEREUM"

        Paypal ->
            "PAYPAL"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PaymentMethodType
fromString enumString =
    case enumString of
        "BITCOIN" ->
            Just Bitcoin

        "EOS" ->
            Just Eos

        "ETHEREUM" ->
            Just Ethereum

        "PAYPAL" ->
            Just Paypal

        _ ->
            Nothing
