-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Cambiatus.Enum.SearchByFields exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Account - Search by member account
  - Bio - Search by member bio
  - Email - Search by member email
  - Name - Search by member name

-}
type SearchByFields
    = Account
    | Bio
    | Email
    | Name


list : List SearchByFields
list =
    [ Account, Bio, Email, Name ]


decoder : Decoder SearchByFields
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "account" ->
                        Decode.succeed Account

                    "bio" ->
                        Decode.succeed Bio

                    "email" ->
                        Decode.succeed Email

                    "name" ->
                        Decode.succeed Name

                    _ ->
                        Decode.fail ("Invalid SearchByFields type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SearchByFields -> String
toString enum =
    case enum of
        Account ->
            "account"

        Bio ->
            "bio"

        Email ->
            "email"

        Name ->
            "name"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SearchByFields
fromString enumString =
    case enumString of
        "account" ->
            Just Account

        "bio" ->
            Just Bio

        "email" ->
            Just Email

        "name" ->
            Just Name

        _ ->
            Nothing
